#!/usr/bin/env bash
# Configures /etc/hosts to redirect localhost and facebook.com safely in Docker
sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > /tmp/hosts.tmp
cat /tmp/hosts.tmp > /etc/hosts
rm /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /etc/hosts
